<%@page import="in.co.rays.proj4.controller.ReportListCtl"%>
<%@page import="in.co.rays.proj4.bean.ReportBean"%>
<%@page import="in.co.rays.proj4.controller.ORSView"%>
<%@page import="in.co.rays.proj4.util.DataUtility"%>
<%@page import="in.co.rays.proj4.util.ServletUtility"%>
<%@page import="java.util.List"%>
<%@page import="java.util.Iterator"%>
<%@page import="java.text.SimpleDateFormat"%>

<html>
<head>
    <title>Report List</title>
    <link rel="icon" type="image/png" href="<%=ORSView.APP_CONTEXT%>/img/logo.png" sizes="16x16" />
</head>
<body>
    <%@include file="Header.jsp"%>

    <jsp:useBean id="bean" class="in.co.rays.proj4.bean.ReportBean" scope="request"></jsp:useBean>

    <div align="center">
        <h1 align="center" style="margin-bottom: -15; color: navy;">Report List</h1>

        <div style="height: 15px; margin-bottom: 12px">
            <h3><font color="red"><%=ServletUtility.getErrorMessage(request)%></font></h3>
            <h3><font color="green"><%=ServletUtility.getSuccessMessage(request)%></font></h3>
        </div>

        <form action="<%=ORSView.REPORT_LIST_CTL%>" method="post">
            <%
                int pageNo = ServletUtility.getPageNo(request);
                int pageSize = ServletUtility.getPageSize(request);
                int index = ((pageNo - 1) * pageSize) + 1;
                int nextListSize = DataUtility.getInt(request.getAttribute("nextListSize").toString());

                List<ReportBean> list = (List<ReportBean>) ServletUtility.getList(request);
                Iterator<ReportBean> it = list.iterator();

                if (list.size() != 0) {
            %>

            <input type="hidden" name="pageNo" value="<%=pageNo%>">
            <input type="hidden" name="pageSize" value="<%=pageSize%>">

            <table style="width: 100%">
                <tr>
                    <td align="center">
                        <label><b>Report Name :</b></label>
                        <input type="text" name="reportName" placeholder="Enter Report Name" value="<%=ServletUtility.getParameter("reportName", request)%>">&emsp;

                        <label><b>Generated By :</b></label>
                        <input type="text" name="generatedBy" placeholder="Enter Generated By" value="<%=ServletUtility.getParameter("generatedBy", request)%>">&emsp;

                        <label><b>Status :</b></label>
                        <input type="text" name="reportStatus" placeholder="Enter Status" value="<%=ServletUtility.getParameter("reportStatus", request)%>">&emsp;

                        <input type="submit" name="operation" value="<%=ReportListCtl.OP_SEARCH%>">
                        &nbsp;
                        <input type="submit" name="operation" value="<%=ReportListCtl.OP_RESET%>">
                    </td>
                </tr>
            </table>
            <br>

            <table border="1" style="width: 100%; border: groove;">
                <tr style="background-color: #e1e6f1e3;">
                    <th width="5%"><input type="checkbox" id="selectall" /></th>
                    <th width="5%">S.No</th>
                    <th width="25%">Report Name</th>
                    <th width="15%">Generated By</th>
                    <th width="15%">Generated Date</th>
                    <th width="10%">Status</th>
                    <th width="5%">Edit</th>
                </tr>

                <%
                    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                    while (it.hasNext()) {
                        bean = (ReportBean) it.next();
                        String date = sdf.format(bean.getGeneratedDate());
                %>

                <tr>
                    <td style="text-align: center;">
                        <input type="checkbox" class="case" name="ids" value="<%=bean.getId()%>">
                    </td>
                    <td style="text-align: center;"><%=index++%></td>
                    <td style="text-align: center; text-transform: capitalize;"><%=bean.getReportName()%></td>
                    <td style="text-align: center; text-transform: capitalize;"><%=bean.getGeneratedBy()%></td>
                    <td style="text-align: center;"><%=date%></td>
                    <td style="text-align: center; text-transform: capitalize;"><%=bean.getReportStatus()%></td>
                    <td style="text-align: center;">
                        <a href="ReportCtl?id=<%=bean.getId()%>">Edit</a>
                    </td>
                </tr>

                <%
                    }
                %>
            </table>

            <table style="width: 100%">
                <tr>
                    <td style="width: 25%">
                        <input type="submit" name="operation" value="<%=ReportListCtl.OP_PREVIOUS%>" <%=pageNo > 1 ? "" : "disabled"%>>
                    </td>
                    <td align="center" style="width: 25%">
                        <input type="submit" name="operation" value="<%=ReportListCtl.OP_NEW%>">
                    </td>
                    <td align="center" style="width: 25%">
                        <input type="submit" name="operation" value="<%=ReportListCtl.OP_DELETE%>">
                    </td>
                    <td style="width: 25%" align="right">
                        <input type="submit" name="operation" value="<%=ReportListCtl.OP_NEXT%>" <%=nextListSize != 0 ? "" : "disabled"%>>
                    </td>
                </tr>
            </table>

            <%
                } else {
            %>

            <table>
                <tr>
                    <td align="right">
                        <input type="submit" name="operation" value="<%=ReportListCtl.OP_BACK%>">
                    </td>
                </tr>
            </table>

            <%
                }
            %>
        </form>
    </div>
     <%@ include file="Footer.jsp"%>
</body>
</html>
