<%@page import="in.co.rays.proj4.bean.ReportBean"%>
<%@page import="in.co.rays.proj4.controller.ORSView"%>
<%@page import="in.co.rays.proj4.controller.ReportCtl"%> 
<%@page import="java.util.HashMap"%>
<%@page import="in.co.rays.proj4.util.DataUtility"%>
<%@page import="in.co.rays.proj4.util.ServletUtility"%>
<%@page import="in.co.rays.proj4.util.HTMLUtility"%>
<html>
<head>
<title>Add Report</title>
<link rel="icon" type="image/png" href="<%=ORSView.APP_CONTEXT%>/img/logo.png" sizes="16x16" />
</head>
<body>
    <form action="<%=ORSView.REPORT_CTL%>" method="post">

        <%@ include file="Header.jsp"%>

        <jsp:useBean id="bean" class="in.co.rays.proj4.bean.ReportBean" scope="request"></jsp:useBean>

        <%
            // Status map example (Pending, Completed, etc.)
            HashMap<String, String> statusMap = new HashMap<String, String>();
            statusMap.put("Pending", "Pending");
            statusMap.put("Completed", "Completed");
            statusMap.put("Cancelled", "Cancelled");
        %>

        <div align="center">
            <h1 align="center" style="margin-bottom: -15; color: navy">
                <%
                    if (bean != null && bean.getId() > 0) {
                %>Update<%
                    } else {
                %>Add<%
                    }
                %>
                Report
            </h1>

            <div style="height: 15px; margin-bottom: 12px">
                <H3 align="center">
                    <font color="red"> <%=ServletUtility.getErrorMessage(request)%> </font>
                </H3>
                <H3 align="center">
                    <font color="green"> <%=ServletUtility.getSuccessMessage(request)%> </font>
                </H3>
            </div>

            <!-- Hidden fields for ID, created/modified info -->
            <input type="hidden" name="id" value="<%=bean.getId()%>">
            <input type="hidden" name="createdBy" value="<%=bean.getCreatedBy()%>">
            <input type="hidden" name="modifiedBy" value="<%=bean.getModifiedBy()%>">
            <input type="hidden" name="createdDatetime" value="<%=DataUtility.getTimestamp(bean.getCreatedDatetime())%>">
            <input type="hidden" name="modifiedDatetime" value="<%=DataUtility.getTimestamp(bean.getModifiedDatetime())%>">

            <table >
                <tr>
                    <th align="left">Report Name<span style="color: red">*</span></th>
                    <td><input type="text" name="reportName" placeholder="Enter Report Name"
                        value="<%=DataUtility.getStringData(bean.getReportName())%>"></td>
                    <td style="position: fixed;">
                        <font color="red"><%=ServletUtility.getErrorMessage("reportName", request)%></font>
                    </td>
                </tr>
                <tr>
                    <th align="left">Generated Date<span style="color: red">*</span></th>
                    <td><input type="text" name="generatedDate" id="udate" placeholder="Select Generated Date"
                        value="<%=DataUtility.getDateString(bean.getGeneratedDate())%>"></td>
                    <td style="position: fixed;">
                        <font color="red"><%=ServletUtility.getErrorMessage("generatedDate", request)%></font>
                    </td>
                </tr>
                <tr>
                    <th align="left">Generated By<span style="color: red">*</span></th>
                    
                    <td><input type="text" name="generatedBy" placeholder="Enter Generated By"
                    
                        value="<%=DataUtility.getStringData(bean.getGeneratedBy())%>"></td>
                        
                    <td style="position: fixed;">
                        <font color="red"><%=ServletUtility.getErrorMessage("generatedBy", request)%></font>
                    </td>
                </tr>
                <tr>
                    <th align="left">Report Status<span style="color: red">*</span></th>
                    <td>
                        <%
                            String htmlList = HTMLUtility.getList("reportStatus", bean.getReportStatus(), statusMap);
                        %>
                        <%=htmlList%>
                    </td>
                    <td style="position: fixed;">
                        <font color="red"><%=ServletUtility.getErrorMessage("reportStatus", request)%></font>
                    </td>
                </tr>
                <tr>
                    <th></th>
                    <td></td>
                </tr>
                <tr>
                    <th></th>
                    <%
                        if (bean != null && bean.getId() > 0) {
                    %>
                    <td align="left" colspan="2">
                        <input type="submit" name="operation" value="<%=ReportCtl.OP_UPDATE%>">
                        <input type="submit" name="operation" value="<%=ReportCtl.OP_CANCEL%>">
                    <%
                        } else {
                    %>
                    <td align="left" colspan="2">
                        <input type="submit" name="operation" value="<%=ReportCtl.OP_SAVE%>">
                        <input type="submit" name="operation" value="<%=ReportCtl.OP_RESET%>">
                    <%
                        }
                    %>
                </tr>
            </table>
        </div>
    </form>
    <%@ include file="Footer.jsp"%>
</body>
</html>
