package in.co.rays.proj4.controller;

import java.io.IOException;
import java.util.HashMap;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;

import in.co.rays.proj4.bean.BaseBean;
import in.co.rays.proj4.bean.ReportBean;
import in.co.rays.proj4.exception.ApplicationException;
import in.co.rays.proj4.exception.DuplicateRecordException;
import in.co.rays.proj4.model.ReportModel;
import in.co.rays.proj4.util.DataUtility;
import in.co.rays.proj4.util.DataValidator;
import in.co.rays.proj4.util.PropertyReader;
import in.co.rays.proj4.util.ServletUtility;

/**
 * Report Controller
 * Handles add, update, reset, and cancel operations for Report
 * @author Pranita
 */
@WebServlet(name = "ReportCtl", urlPatterns = { "/ctl/ReportCtl" })
public class ReportCtl extends BaseCtl {

    private static Logger log = Logger.getLogger(ReportCtl.class);

    /**
     * Preload any dropdowns (if required)
     */
    @Override
    protected void preload(HttpServletRequest request) {
        HashMap<String, String> statusMap = new HashMap<>();
        statusMap.put("Pending", "Pending");
        statusMap.put("Completed", "Completed");
        statusMap.put("Cancelled", "Cancelled");
        request.setAttribute("statusMap", statusMap);
    }

    /**
     * Validate user input
     */
    @Override
    protected boolean validate(HttpServletRequest request) {
        boolean pass = true;

        if (DataValidator.isNull(request.getParameter("reportName"))) {
            request.setAttribute("reportName",
                    PropertyReader.getValue("error.require", "Report Name"));
            pass = false;
        }

        if (DataValidator.isNull(request.getParameter("generatedDate"))) {
            request.setAttribute("generatedDate",
                    PropertyReader.getValue("error.require", "Generated Date"));
            pass = false;
        } else if (!DataValidator.isDate(request.getParameter("generatedDate"))) {
            request.setAttribute("generatedDate",
                    PropertyReader.getValue("error.date", "Generated Date"));
            pass = false;
        }

        if (DataValidator.isNull(request.getParameter("generatedBy"))) {
            request.setAttribute("generatedBy",
                    PropertyReader.getValue("error.require", "Generated By"));
            pass = false;
        }

        if (DataValidator.isNull(request.getParameter("reportStatus"))) {
            request.setAttribute("reportStatus",
                    PropertyReader.getValue("error.require", "Report Status"));
            pass = false;
        }

        return pass;
    }

    /**
     * Populate bean from request
     */
    @Override
    protected BaseBean populateBean(HttpServletRequest request) {
        ReportBean bean = new ReportBean();

        bean.setId(DataUtility.getLong(request.getParameter("id")));
        bean.setReportName(DataUtility.getString(request.getParameter("reportName")));
        bean.setGeneratedDate(DataUtility.getDate(request.getParameter("generatedDate")));
        bean.setGeneratedBy(DataUtility.getString(request.getParameter("generatedBy")));
       
        populateDTO(bean, request);
        
        return bean;
    }

    /**
     * Display Report form
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        long id = DataUtility.getLong(request.getParameter("id"));
        ReportModel model = new ReportModel();

        if (id > 0) {
            try {
                ReportBean bean = model.findByPk(id);
                ServletUtility.setBean(bean, request);
            } catch (ApplicationException e) {
                log.error("Error in ReportCtl doGet", e);
                ServletUtility.handleException(e, request, response);
                return;
            }
        }
        ServletUtility.forward(getView(), request, response);
    }

    /**
     * Handle form submission (save/update/reset/cancel)
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        String op = DataUtility.getString(request.getParameter("operation"));
        ReportModel model = new ReportModel();
        long id = DataUtility.getLong(request.getParameter("id"));

        if (OP_SAVE.equalsIgnoreCase(op) || OP_UPDATE.equalsIgnoreCase(op)) {

            ReportBean bean = (ReportBean) populateBean(request);

            try {
                if (OP_SAVE.equalsIgnoreCase(op)) {
                    model.add(bean);
                    ServletUtility.setSuccessMessage("Report added successfully", request);
                } else if (OP_UPDATE.equalsIgnoreCase(op) && id > 0) {
                    model.update(bean);
                    ServletUtility.setSuccessMessage("Report updated successfully", request);
                }
                ServletUtility.setBean(bean, request);

            } catch (DuplicateRecordException e) {
                ServletUtility.setBean(bean, request);
                ServletUtility.setErrorMessage("Report already exists", request);
            } catch (ApplicationException e) {
                log.error("Error in ReportCtl doPost", e);
                ServletUtility.handleExceptionDB(getView(), request, response);

                return;
            }

        } else if (OP_CANCEL.equalsIgnoreCase(op)) {
            ServletUtility.redirect(ORSView.REPORT_LIST_CTL, request, response);
            return;
        } else if (OP_RESET.equalsIgnoreCase(op)) {
            ServletUtility.redirect(ORSView.REPORT_CTL, request, response);
            return;
        }

        ServletUtility.forward(getView(), request, response);
    }

    @Override
    protected String getView() {
        return ORSView.REPORT_VIEW;
    }
}
